const csd_version = '3/2/2023'
var programma = [
	{
		class: 'ΗΥ-109',
		name: 'Αγγλικά IΙ',
		teacher: 'ΡΙΖΟΠΟΥΛΟΥ',
		monday: '10-12 Η.204',
		tuesday: '',
		wednesday: '10-12 Η.204',
		thursday: '',
		friday: '',
		time_score: 10
	},
	{
		class: 'ΗΥ-111',
		name: 'Απειροστικός Λογισμός ΙΙ',
		teacher: 'ΠΙΤΙΚΑΚΗΣ / ΤΣΑΓΚΑΤΑΚΗΣ',
		monday: '',
		tuesday: '2-4 ΑΜΦ Α',
		wednesday: '',
		thursday: '12-2 ΑΜΦ Α',
		friday: '2-4 ΑΜΦ Α (ΦΡΟΝΤ)',
		time_score: 14
	},
	{
		class: 'ΗΥ-118',
		name: '∆ιακριτά Μαθηματικά',
		teacher: 'ΑΡΓΥΡΟΣ',
		monday: '',
		tuesday: '10-12 ΑΜΦ ΣΟ',
		wednesday: '',
		thursday: '10-12 ΑΜΦ ΣΟ',
		friday: '10-12 ΑΜΦ Α (ΦΡΟΝΤ)',
		time_score: 10
	},
	{
		class: 'ΗΥ-119',
		name: 'Γραμμική Άλγεβρα',
		teacher: 'ΤΣΑΜΑΡ∆ΙΝΟΣ',
		monday: '2-4 ΑΜΦ ΣΟ',
		tuesday: '',
		wednesday: '',
		thursday: '2-4 ΑΜΦ Α',
		friday: '4-6 ΑΜΦ ΣΟ (ΦΡΟΝΤ)',
		time_score: 14
	},
	{
		class: 'ΗΥ-150',
		name: 'Προγραμματισμός',
		teacher: 'ΠΑΠΑΓΙΑΝΝΑΚΗΣ',
		monday: '6-8 ΑΜΦ ΣΟ',
		tuesday: '',
		wednesday: '6-8 ΑΜΦ ΣΟ',
		thursday: '',
		friday: '6-8 ΑΜΦ ΣΟ (ΦΡΟΝΤ)',
		time_score: 18
	},
	{
		class: 'ΗΥ-180',
		name: 'Λογική',
		teacher: 'ΠΛΕΞΟΥΣΑΚΗΣ / ΠΙΤΙΚΑΚΗΣ',
		monday: '4-6 ΑΜΦ ΣΟ',
		tuesday: '',
		wednesday: '4-6 ΑΜΦ ΣΟ',
		thursday: '4-6 ΑΜΦ ΣΟ (ΦΡΟΝΤ)',
		friday: '',
		time_score: 16
	},
	{
		class: 'ΗΥ-209',
		name: 'Αγγλικά IV',
		teacher: 'ΡΙΖΟΠΟΥΛΟΥ',
		monday: '',
		tuesday: '10-12 Η.204',
		wednesday: '',
		thursday: '10-12 Η.204',
		friday: '',
		time_score: 10
	},
	{
		class: 'ΗΥ-215',
		name: 'Εφαρμοσμένα Μαθηματικά για Μηχανικούς',
		teacher: 'ΣΤΥΛΙΑΝΟΥ / ΚΑΦΕΝΤΖΗΣ',
		monday: '',
		tuesday: '2-4 ΑΜΦ ΣΟ',
		wednesday: '',
		thursday: '2-4 ΑΜΦ ΣΟ',
		friday: '2-4 ΑΜΦ ΣΟ (ΦΡΟΝΤ)',
		time_score: 14
	},
	{
		class: 'ΗΥ-220',
		name: 'Εργαστήριο Ψηφιακών Κυκλωμάτων',
		teacher: 'ΠΑΠΑΕΥΣΤΑΘΙΟΥ',
		monday: '2-4 Α.125',
		tuesday: '',
		wednesday: '2-4 Α.125',
		thursday: '',
		friday: '',
		time_score: 14
	},
	{
		class: 'ΗΥ-225',
		name: 'Οργάνωση Υπολογιστών',
		teacher: 'ΚΑΤΕΒΑΙΝΗΣ',
		monday: '12-2 ΑΜΦ ΣΟ',
		tuesday: '',
		wednesday: '12-2 ΑΜΦ ΣΟ',
		thursday: '',
		friday: '12-2 ΑΜΦ ΣΟ',
		time_score: 12
	},
	{
		class: 'ΗΥ-255',
		name: 'Εργαστήριο Λογισμικού',
		teacher: 'ΜΠΙΛΑΣ',
		monday: '10-12 ΑΜΦ ΣΟ',
		tuesday: '',
		wednesday: '10-12 ΑΜΦ ΣΟ',
		thursday: '',
		friday: '10-12 ΑΜΦ ΣΟ (ΦΡΟΝΤ)',
		time_score: 10
	},
	{
		class: 'ΗΥ-317',
		name: 'Εφαρμοσμένες Στοχαστικές ∆ιαδικασίες',
		teacher: 'ΤΣΑΚΑΛΙ∆ΗΣ',
		monday: '10-12 ΑΜΦ Α',
		tuesday: '',
		wednesday: '10-12 ΑΜΦ Α',
		thursday: '',
		friday: '12-2 ΑΜΦ Α (ΦΡΟΝΤ)',
		time_score: 10
	},
	{
		class: 'ΗΥ-335',
		name: '∆ίκτυα Υπολογιστών',
		teacher: '∆ΗΜΗΤΡΟΠΟΥΛΟΣ',
		monday: '10-12 Α.113',
		tuesday: '',
		wednesday: '10-12 Α.113',
		thursday: '',
		friday: '2-4 Α.113 (ΦΡΟΝΤ)',
		time_score: 10
	},
	{
		class: 'ΗΥ-340',
		name: 'Γλώσσες και Μεταφραστές',
		teacher: 'ΣΑΒΒΙ∆ΗΣ',
		monday: '',
		tuesday: '10-12 ΑΜΦ Α',
		wednesday: '',
		thursday: '10-12 ΑΜΦ Α',
		friday: '10-12 Η.204 (ΦΡΟΝΤ)',
		time_score: 10
	},
	{
		class: 'ΗΥ-342',
		name: 'Παράλληλος Προγραμματισμός',
		teacher: 'ΠΡΑΤΙΚΑΚΗΣ',
		monday: '',
		tuesday: '2-4 Η.204',
		wednesday: '',
		thursday: '2-4 Η.204',
		friday: '',
		time_score: 14
	},
	{
		class: 'ΗΥ-351',
		name: 'Ανάλυση και Σχεδίαση Πληροφοριακών Συστημάτων',
		teacher: 'ΕΥΘΥΜΙΟΥ',
		monday: '2-4 ΑΜΦ Α',
		tuesday: '',
		wednesday: '2-4 ΑΜΦ Α',
		thursday: '',
		friday: '6-8 ΑΜΦ Α (ΦΡΟΝΤ)',
		time_score: 14
	},
	{
		class: 'ΗΥ-364',
		name: 'Εισαγωγή στην Αλληλεπίδραση Ανθρώπου - Υπολογιστή',
		teacher: 'ΣΤΕΦΑΝΙ∆ΗΣ / ΛΕΩΝΙ∆ΗΣ',
		monday: '4-6 ΑΜΦ Α',
		tuesday: '',
		wednesday: '4-6 ΑΜΦ Α',
		thursday: '',
		friday: '4-6 ΑΜΦ Α (ΦΡΟΝΤ)',
		time_score: 16
	},
	{
		class: 'ΗΥ-380',
		name: 'Αλγόριθμοι και Πολυπλοκότητα',
		teacher: 'ΤΟΛΛΗΣ',
		monday: '12-2 ΑΜΦ Α',
		tuesday: '',
		wednesday: '12-2 ΑΜΦ Α',
		thursday: '6-8 ΑΜΦ Α (ΦΡΟΝΤ)',
		friday: '',
		time_score: 12
	},
	{
		class: 'ΗΥ-390.51',
		name: 'Εισαγωγη στη γλωσσα R για Βιοπληροφορική',
		teacher: 'ΤΣΑΜΑΡ∆ΙΝΟΣ / ΠΑΥΛΙ∆ΗΣ',
		monday: '',
		tuesday: '12-2 ΑΜΦ ΣΟ',
		wednesday: '',
		thursday: '12-2 ΑΜΦ ΣΟ',
		friday: '',
		time_score: 12
	},
	{
		class: 'ΗΥ-428',
		name: 'Εργαστήριο Ενσωματωμένων Συστημάτων',
		teacher: 'ΜΠΙΛΑΣ / ΜΑΡΑΖΑΚΗΣ',
		monday: '4-6 Α.113',
		tuesday: '',
		wednesday: '4-6 Α.113',
		thursday: '',
		friday: '4-6 Α.113 (ΦΡΟΝΤ)',
		time_score: 16
	},
	{
		class: 'ΗΥ-435',
		name: 'Εργαστήριο Τεχνολογίας και Προγραμματισμού ∆ικτύων Ι',
		teacher: 'ΤΡΑΓΑΝΙΤΗΣ / ΠΑΠΑ∆ΑΚΗΣ ΣΤ .',
		monday: '',
		tuesday: '12-2 Η.204',
		wednesday: '',
		thursday: '12-2 Η.204',
		friday: '',
		time_score: 12
	},
	{
		class: 'ΗΥ-439',
		name: 'Κινητά Υπολογιστικά Συστήματα',
		teacher: 'ΠΑΠΑ∆ΟΠΟΥΛΗ',
		monday: '',
		tuesday: '4-6 Α.125',
		wednesday: '',
		thursday: '4-6 Η.204',
		friday: '4-6 Η.204 (ΦΡΟΝΤ)',
		time_score: 16
	},
	{
		class: 'ΗΥ-446',
		name: 'Συστήματα Εκτέλεσης ∆υναμικών Γλωσσών Προγραμματισμού',
		teacher: 'ΘΕΣΗ ΕΝΤΕΤΑΛΜΕΝΟΥ ∆Ι∆ΑΣΚΟΝΤΑ',
		monday: '',
		tuesday: '10-12 Α.125',
		wednesday: '',
		thursday: '10-12 Α.125',
		friday: '10-12 Α.125 (ΦΡΟΝΤ)',
		time_score: 10
	},
	{
		class: 'ΗΥ-455',
		name: 'Εργαστήριο ∆ιαδικτυακών Επιθέσεων και Αμυντικών Τεχνικών',
		teacher: 'ΘΕΣΗ ΕΝΤΕΤΑΛΜΕΝΟΥ ∆Ι∆ΑΣΚΟΝΤΑ',
		monday: '2-4 Η.208',
		tuesday: '',
		wednesday: '2-4 Η.208 (ΦΡΟΝΤ)',
		thursday: '2-4 Η.208',
		friday: '',
		time_score: 14
	},
	{
		class: 'ΗΥ-457',
		name: 'Εισαγωγή στα Συστήματα Ασφάλειας Πληροφοριών',
		teacher: 'ΜΑΡΚΑΤΟΣ',
		monday: '',
		tuesday: '2-4 Α.113',
		wednesday: '',
		thursday: '2-4 Α.113',
		friday: '2-4 Η.204 (ΦΡΟΝΤ)',
		time_score: 14
	},
	{
		class: 'ΗΥ-463',
		name: 'Συστήματα Ανάκτησης Πληροφοριών',
		teacher: 'ΤΖΙΤΖΙΚΑΣ',
		monday: '',
		tuesday: '',
		wednesday: '10-2 Α.121',
		thursday: '',
		friday: '10-12 Α.113 (ΦΡΟΝΤ)',
		time_score: 10
	},
	{
		class: 'ΗΥ-472',
		name: 'Υπολογιστική Όραση',
		teacher: 'ΑΡΓΥΡΟΣ',
		monday: '12-2 Ε.313',
		tuesday: '',
		wednesday: '12-2 Ε.313',
		thursday: '',
		friday: '2-4 Ε.313',
		time_score: 12
	},
	{
		class: 'ΗΥ-473',
		name: 'Αναγνώριση Προτύπων',
		teacher: 'ΤΡΑΧΑΝΙΑΣ',
		monday: '',
		tuesday: '2-4 Α.125',
		wednesday: '',
		thursday: '2-4 Α.125',
		friday: '',
		time_score: 14
	},
	{
		class: 'ΗΥ-475',
		name: 'Αυτόνομη Ρομποτική Πλοήγηση',
		teacher: 'ΤΡΑΧΑΝΙΑΣ',
		monday: '',
		tuesday: '10-12 Η.206',
		wednesday: '',
		thursday: '10-12 Η.206',
		friday: '',
		time_score: 10
	},
	{
		class: 'ΗΥ-500',
		name: 'Εισαγωγή στην Ερευνα',
		teacher: 'ΜΕΛΗ ∆ΕΠ ΤΟΥ ΤΜΗΜΑΤΟΣ',
		monday: '',
		tuesday: '',
		wednesday: '',
		thursday: '4-6 ΑΜΦ Α',
		friday: '',
		time_score: 16
	},
	{
		class: 'ΗΥ-523',
		name: 'Εργαστηριακή Σχεδίαση Ψηφιακών Κυκλωμάτων με Εργαλεία Ηλεκτρονικού Αυτοματισμού',
		teacher: 'ΠΑΠΑΕΥΣΤΑΘΙΟΥ',
		monday: '',
		tuesday: '6-8 Η.206',
		wednesday: '',
		thursday: '',
		friday: '6-8 Η.206',
		time_score: 18
	},
	{
		class: 'ΗΥ-534',
		name: 'Αρχιτεκτονική Μεταγωγέων Πακέτων',
		teacher: 'ΚΑΤΕΒΑΙΝΗΣ / ΧΡΥΣΟΣ',
		monday: '12-2 Η.206',
		tuesday: '',
		wednesday: '12-2 Η.206',
		thursday: '',
		friday: '',
		time_score: 12
	},
	{
		class: 'ΗΥ-540',
		name: 'Προχωρημένα Θέματα Ανάπτυξης Γλωσσών Προγραμματισμού',
		teacher: 'ΣΑΒΒΙ∆ΗΣ',
		monday: '',
		tuesday: '',
		wednesday: '12-2 Η.208',
		thursday: '',
		friday: '12-2 Η.208',
		time_score: 12
	},
	{
		class: 'ΗΥ-543',
		name: 'Συστήματα Λογισμικού και Τεχνολογίες για Εφαρμογές Μεγάλου Όγκου ∆εδομένων',
		teacher: 'ΜΠΙΛΑΣ / ΚΟΖΑΝΙΤΗΣ',
		monday: '4-6 Η.206',
		tuesday: '',
		wednesday: '4-6 Η.206',
		thursday: '',
		friday: '4-6 Η.206',
		time_score: 16
	},
	{
		class: 'ΗΥ-548',
		name: 'Αρχιτεκτονικές Λογισμικού για το Υπολογιστικό Νέφος',
		teacher: 'ΜΠΙΛΑΣ / ΧΑΖΑΠΗΣ',
		monday: '2-4 Η.206',
		tuesday: '',
		wednesday: '2-4 Η.206',
		thursday: '',
		friday: '2-4 Η.206',
		time_score: 14
	},
	{
		class: 'ΗΥ-553',
		name: '∆ιαδραστικά Γραφικά Υπολογιστών',
		teacher: 'ΚΑΜΑΡΙΑΝΑΚΗΣ',
		monday: '',
		tuesday: '10-12 Η.208',
		wednesday: '',
		thursday: '10-12 Η.208',
		friday: '12-2 Α.125',
		time_score: 10
	},
	{
		class: 'ΗΥ-561',
		name: '∆ιαχείριση ∆εδομένων στον Παγκόσμιο Ιστό',
		teacher: 'ΤΖΙΤΖΙΚΑΣ',
		monday: '10-2 Η.208',
		tuesday: '',
		wednesday: '',
		thursday: '',
		friday: '',
		time_score: 10
	},
	{
		class: 'ΗΥ-563',
		name: 'Προχωρημένα Θέματα Ανάκτησης Πληροφοριών',
		teacher: 'ΜΟΥΝΤΑΝΤΩΝΑΚΗΣ',
		monday: '2-4 Α.121',
		tuesday: '',
		wednesday: '2-4 Α.121',
		thursday: '',
		friday: '2-4 Α.121',
		time_score: 14
	},
	{
		class: 'ΗΥ-565',
		name: 'Συστήματα ∆ιαχείρισης ∆ιεργασιών',
		teacher: 'ΠΛΕΞΟΥΣΑΚΗΣ / ΖΕΓΚΙΝΗΣ / ΚΡΗΤΙΚΟΣ',
		monday: '',
		tuesday: '',
		wednesday: '10-12 Η.208',
		thursday: '10-12 Α.121',
		friday: '',
		time_score: 10
	},
	{
		class: 'ΗΥ-569',
		name: 'Συμπόρευση Ανθρώπου – Υπολογιστή',
		teacher: 'ΣΤΕΦΑΝΙ∆ΗΣ',
		monday: '',
		tuesday: '6-8 Η.208',
		wednesday: '',
		thursday: '6-8 Η.208',
		friday: '10-12 Η.208',
		time_score: 18
	},
	{
		class: 'ΗΥ-586',
		name: 'Κατανεμημένος Υπολογισμός',
		teacher: 'ΦΑΤΟΥΡΟΥ',
		monday: '',
		tuesday: '2-4 Η.208',
		wednesday: '2-4 Η.204',
		thursday: '',
		friday: '4-6 Α.121 (ΦΡΟΝΤ)',
		time_score: 14
	},
	{
		class: 'ΗΥ-587',
		name: 'Νευρωνικά ∆ίκτυα και Μάθηση Ιεραρχικών Αναπαραστάσεων',
		teacher: 'ΚΟΜΟΝΤΑΚΗΣ',
		monday: '6-8 Η.204',
		tuesday: '',
		wednesday: '6-8 Η.204',
		thursday: '',
		friday: '',
		time_score: 18
	},
	{
		class: 'ΗΥ-588',
		name: 'Ανάλυση και Μοντελοποίηση ∆ικτύων του Εγκεφάλου',
		teacher: 'ΠΑΠΑ∆ΟΠΟΥΛΗ',
		monday: '4-6 Η.204',
		tuesday: '',
		wednesday: '4-6 Η.204',
		thursday: '',
		friday: '4-6 Α.125',
		time_score: 16
	},
	{
		class: 'ΗΥ-590.31',
		name: '∆ιαδίκτυο των Αντικειμένων για την Έξυπνη Πόλη',
		teacher: 'ΑΓΓΕΛΑΚΗΣ',
		monday: '12-2 Α.125',
		tuesday: '',
		wednesday: '12-2 Α.125',
		thursday: '',
		friday: '',
		time_score: 12
	},
	{
		class: 'ΗΥ-590.45',
		name: 'Σύγχρονα Θέματα Κλιμακώσιμων Συστημάτων Αποθήκευσης',
		teacher: 'ΜΑΓΚΟΥΤΗΣ',
		monday: '',
		tuesday: '12-2 Η.208',
		wednesday: '',
		thursday: '12-2 Η.208',
		friday: '12-2 Α.121',
		time_score: 12
	},
	{
		class: 'ΗΥ-673',
		name: 'Εισαγωγή στην Γέννηση ∆εδομένων με Βαθιά Μάθηση',
		teacher: 'ΣΤΥΛΙΑΝΟΥ / ΠΑΝΤΑΖΗΣ',
		monday: '10-12 Η.206',
		tuesday: '',
		wednesday: '10-12 Η.206',
		thursday: '',
		friday: '10-12 Η.206 (ΦΡΟΝΤ)',
		time_score: 10
	},
	{
		class: 'ΗΥ-693',
		name: 'Εισαγωγή στη Θεωρία Παιγνίων',
		teacher: 'ΤΡΑΓΑΝΙΤΗΣ / ΦΑΣΟΥΛΑΚΗΣ',
		monday: '',
		tuesday: '4-6 Η.208',
		wednesday: '',
		thursday: '',
		friday: '4-6 Η.208',
		time_score: 16
	},
]